##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.1.0] date: [Mon Feb 03 19:54:27 CET 2020] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = firmware


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization for size
OPT = -Os


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_adc.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_can.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_cec.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_cmp.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_crc.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_dac.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_dbg.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_dma.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_exti.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_fmc.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_fwdgt.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_gpio.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_i2c.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_ivref.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_misc.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_opa.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_pmu.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_rcu.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_rtc.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_slcd.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_spi.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_syscfg.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_timer.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_tsi.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_usart.c \
Drivers/GD32F1x0_standard_peripheral/Source/gd32f1x0_wwdgt.c \
Drivers/CMSIS/Source/system_gd32f1x0.c \
Src/main.c \
Src/util.c \
Src/systick.c \
Src/mpu6050.c \
Src/mpu6050_dmp.c \
Src/setup.c \
Src/i2c_it.c \
Src/gd32f1x0_it.c

# ASM sources
ASM_SOURCES =  \
startup_gd32f1x0.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DGD32F130_150


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/GD32F1x0_standard_peripheral/Include \
-IDrivers/CMSIS/Include \
-IDrivers/CMSIS 

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32F130C6_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

flash:
	st-flash --reset write $(BUILD_DIR)/$(TARGET).bin 0x8000000

unlock:
	openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg -c init -c "reset halt" -c "stm32f1x unlock 0"
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
